server:
  port: 8001

spring:
  application:
    name: payment-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:2001/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true